<%
deployment_name = "clair"
director_uuid = "CHANGE-ME"
%>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
  - name: clair
    version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  canaries: 0
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    type: manual
    subnets:
      - cloud_properties: {}
        range: 10.244.0.0/24
        reserved:
          - 10.244.0.1
        static:
          - 10.244.0.2

resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties: {}

jobs:
  - name: clair
    templates:
      - name: clair
    instances: 1
    resource_pool: default
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.244.0.2

properties:
  clair:
    log_level: debug
